### ISSUE TITLE
Pre-Review MultipleArbitrableTransactionWithAppeals.sol

### ISSUE THREAD

**Issue by epiqueras** [kleros/escrow-contracts#2]
https://docs.google.com/document/d/1BSWCDNEVySCy0UQYMKsdlNLkhr4xxQ8aqTQXUUXSOVA/edit?usp=sharing

**Comment by epiqueras** [comment]
@unknownunknown1

**Comment by unknownunknown1** [comment]
This version of the contract is developed by @fnanni-0
