### ISSUE TITLE
Review by @nix1g

### ISSUE THREAD

**Issue by nix1g** [kleros/escrow-contracts#5]
# Review @ [`4a682e0`](https://github.com/kleros/escrow-contracts/tree/4a682e03c896af42db2bc53b341601a953a5c09d)
#### Reentrency
[L262](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTokenTransactionWithAppeals.sol#L262) does not prevent reentrency: the variable is only modified in memory and this change is not stored before the call to `transfer`.
## Minor
| [ETH](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTransactionWithAppeals.sol) | [Token](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTokenTransactionWithAppeals.sol) | Issue |
|:-:|:-:|:- |
| [L56](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTransactionWithAppeals.sol#L56) | [L64](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTokenTransactionWithAppeals.sol#L64) | `ruling` should be of type `enum Party`. |
| [L412](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTransactionWithAppeals.sol#L412) | [L437](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTokenTransactionWithAppeals.sol#L437) | Condition can be simplified to `_side != Party.None`. |
| [L427](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTransactionWithAppeals.sol#L427) | [L451](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTokenTransactionWithAppeals.sol#L451) | Expression can be simplified to `block.timestamp < (appealPeriodEnd + appealPeriodStart) / 2`. |
| [L18](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTransactionWithAppeals.sol#L18), [L411-L461](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTransactionWithAppeals.sol#L411-L461) | [L25](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTokenTransactionWithAppeals.sol#L25), [L436-L487](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTokenTransactionWithAppeals.sol#L436-L487) | This is the only place where `CappedMath` is used, and with controlled (i.e. trusted) values. I would remove it altogether. |
| [L419](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTransactionWithAppeals.sol#L419) | [L444](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTokenTransactionWithAppeals.sol#L444) | Variable scoping is not necessary. |

## Consistency issues and linting
- Both files are very similar, they should be easily `diff`-able (aim to reduce discrepencies like the use of `uint` vs `uint256`, trailing spaces, comments wording...).
- To use `solhint` efficiently, you should explicitely state the warnings you want to ignore in the code using `solhint-disable` and `solhint-disable-next-line`.

**Comment by fnanni-0** [comment]
> This is the only place where CappedMath is used, and with controlled (i.e. trusted) values. I would remove it altogether.

I'm not sure about this one. It's not impossible that appealCost changes during the funding of an appeal, which could produce an underflow [here](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTransactionWithAppeals.sol#L439). On the other hand, if for some reason the arbitrator sets the appealCost to a non-payable amount to disable appeals, [this line](https://github.com/kleros/escrow-contracts/blob/4a682e03c896af42db2bc53b341601a953a5c09d/contracts/0.7.x/MultipleArbitrableTransactionWithAppeals.sol#L436) could overflow.

**Comment by nix1g** [comment]
Ok then, let's keep it as is 👍
